apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: infrastructure
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/instance: redis
    app.kubernetes.io/component: database
spec:
  selector:
    app.kubernetes.io/name: redis
    app.kubernetes.io/instance: redis
    app.kubernetes.io/component: database
  type: LoadBalancer
  sessionAffinity: None
  ports:
    - name: redis
      targetPort: redis
      port: 6379
