apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
  namespace: "default"
  labels:
    app.kubernetes.io/name: mysql
    app.kubernetes.io/instance: mysql
    app.kubernetes.io/component: primary
data:
  my.cnf: |
    [mysqld]
    bind-address=*
    default-time-zone=UTC
    default_authentication_plugin=mysql_native_password
    character-set-server=utf8mb4
    collation-server=utf8mb4_unicode_ci
    init_connect='SET NAMES utf8mb4'
    init_connect='SET collation_connection=utf8mb4_unicode_ci'
    max_allowed_packet=16M
    long_query_time=10.0
    slow_query_log=0
    skip-name-resolve
    explicit_defaults_for_timestamp
    basedir=/usr
    datadir=/var/lib/mysql
    tmpdir=/tmp
    socket=/var/run/mysqld/mysqld.sock
    pid-file=/var/run/mysqld/mysqld.pid
    [client]
    port=3306
    socket=/var/run/mysqld/mysqld.sock
    default-character-set='utf8mb4'
    [manager]
    port=3306
    socket=/var/run/mysqld/mysqld.sock
    pid-file=/var/run/mysqld/mysqld.pid

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-scripts
  namespace: "default"
  labels:
    app.kubernetes.io/name: mysql
    app.kubernetes.io/instance: mysql
    app.kubernetes.io/component: primary
data:
  init.sql: |-
    CREATE USER 'admin'@'%' IDENTIFIED BY 'admin';
    GRANT ALL PRIVILEGES ON *.* TO 'admin'@'%' WITH GRANT OPTION;
    FLUSH PRIVILEGES;
