apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq-config
  namespace: infrastructure
  labels:
    app.kubernetes.io/name: rabbitmq
    app.kubernetes.io/instance: rabbitmq
    app.kubernetes.io/component: broker
data:
  rabbitmq.conf: |-
    default_user = admin
