apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rabbitmq-ingress
  namespace: infrastructure
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
  labels:
    app.kubernetes.io/name: rabbitmq
    app.kubernetes.io/component: ingress
spec:
  ingressClassName: traefik
  rules:
    - host: rabbitmq.cluster.local
      http:
        paths:
          - path: ""
            pathType: ImplementationSpecific
            backend:
              service:
                name: rabbitmq-service
                port:
                  name: http-stats
