apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-config
  namespace: infrastructure
  labels:
    app.kubernetes.io/name: mongodb
    app.kubernetes.io/instance: mongodb
    app.kubernetes.io/component: config
data:
  MONGO_INITDB_ROOT_USERNAME: "root"
  ALLOW_EMPTY_PASSWORD: "yes"
  MONGODB_SYSTEM_LOG_VERBOSITY: "0"
  MONGODB_DISABLE_SYSTEM_LOG: "no"
  MONGODB_DISABLE_JAVASCRIPT: "no"
  MONGODB_ENABLE_JOURNAL: "yes"
  MONGODB_PORT_NUMBER: "27017"
  MONGODB_ENABLE_IPV6: "no"
  MONGODB_ENABLE_DIRECTORY_PER_DB: "no"
