apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  namespace: infrastructure
  labels:
    app.kubernetes.io/name: mongodb
    app.kubernetes.io/instance: mongodb
    app.kubernetes.io/component: database
spec:
  type: LoadBalancer
  sessionAffinity: None
  ports:
    - name: mongodb
      port: 27017
      targetPort: mongodb
  selector:
    app.kubernetes.io/name: mongodb
    app.kubernetes.io/instance: mongodb
    app.kubernetes.io/component: database
