apiVersion: v1
kind: Service
metadata:
  name: mongodb-headless
  namespace: infrastructure
  labels:
    app.kubernetes.io/name: mongodb-headless
    app.kubernetes.io/component: service
spec:
  sessionAffinity: None
  type: ClusterIP
  clusterIP: None
  ports:
    - name: mongodb
      port: 27017
      protocol: TCP
      targetPort: mongodb
  selector:
    app.kubernetes.io/name: mongodb
    app.kubernetes.io/instance: mongodb
    app.kubernetes.io/component: database

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: service
    app.kubernetes.io/name: mongodb-service-lb
  name: mongodb-service-lb
  namespace: infrastructure
spec:
  sessionAffinity: None
  type: LoadBalancer
  ports:
    - name: mongodb
      port: 27017
      protocol: TCP
      targetPort: mongodb
  selector:
    app.kubernetes.io/instance: mongodb
    app.kubernetes.io/name: mongodb
    app.kubernetes.io/component: database
